# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Test and Upload Python Package

on:
  push:
    tags:
       - '*'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: s-weigand/setup-conda@v1
        with:
          python-version: 3.6
      - name: Which python
        run: |
          conda --version
          which python
      - name: Install apt packages
        run: |
          sudo apt update
          sudo apt install -y build-essential mpich libmpich-dev libglib2.0-0 libgl1-mesa-glx qt5-default packagekit-gtk3-module libcanberra-gtk-module
      - name: Install dependencies
        run: |
          pip install -e .
          pip install pytest
          pip install setuptools wheel twine
          pip install Cython
          pip install -r requirements_sorters.txt
      - name: Test with pytest and build coverage report
        run: |
          pytest
      - name: Publish on PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
